from typing import Any, Mapping, Protocol
from blackstar.contracts.models import (
    BlackstarIntent, ProposedDSPTransaction, ValidationResult, DSPApplyResult, PerformanceEvent
)

class SpeechRecognizer(Protocol):
    def transcribe(self, audio_frame: bytes) -> str: ...

class IntentAdapter(Protocol):
    def interpret(self, transcript: str, context: Mapping[str, Any]) -> BlackstarIntent: ...

class OntologyRepository(Protocol):
    def version(self) -> str: ...
    def dimension(self, name: str) -> Mapping[str, Any]: ...
    def parameter_rule(self, parameter: str) -> Mapping[str, Any]: ...

class ToneCompiler(Protocol):
    def compile(
        self,
        intent: BlackstarIntent,
        current_tone: Mapping[str, float],
        ontology_version: str,
    ) -> ProposedDSPTransaction: ...

class Validator(Protocol):
    def validate(
        self,
        tx: ProposedDSPTransaction,
        policy: Mapping[str, Any],
    ) -> ValidationResult: ...

class DSPBridge(Protocol):
    def current_preset_version(self) -> str: ...
    def current_tone(self) -> Mapping[str, float]: ...
    def apply_atomic(self, tx: ProposedDSPTransaction) -> DSPApplyResult: ...
    def rollback(self, rollback_token: str) -> DSPApplyResult: ...

class EventStore(Protocol):
    def append(self, event: PerformanceEvent) -> None: ...
    def next_sequence(self) -> int: ...
